name: capo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy=1.26
  - pip
  - pandas
  - pyarrow
  - ray-default>=2.9
  - pytest
  - hydra-core>=1.3
  - omegaconf>=2.3
  - transformers>=4.40
  - accelerate>=0.28
  - datasets
  - wandb
  - matplotlib
  - seaborn
  # Dev tools
  - pre-commit
  - ruff
  - jupyterlab
  # Vendored verl dependencies
  - codetiming
  - cloudpickle
